fix Cannot use ::class with dynamic class name
dynamic-commerce/tree-nodes pull request #11
Opened 2022-09-29 09:06 UTC by baerla

noticed in project lecos

2022-09-29 09:28 UTC, Wulfheart commented
Does lecos need PHP 7.4 or do we have any project that needs this library that relies on PHP 7.4? 
If not we could just bump up the required version as it is supported from PHP 8.0 upwards.

2022-10-04 03:36 UTC, MBauerDC requested changes
For consistency, we should either prepend a "\" to the call to "getClass" in order to call it in its default namespace - or (preferably) create "use"-statements for every built-in function used in this file.

2022-10-04 13:50 UTC, NoNamePaul94 approved these changes
When Michi's change request is dealt with this looks good for me

2022-10-06 13:42 UTC, MBauerDC approved these changes

2022-10-12 13:27 UTC, merged